# Data Analysis 
- helps in analysing data and finding a usefull output
- numpy gives basic libraries for data analysis 

# Numpy

`without numpy doing maths(matrix maths) is very complex in any language`
- create array
- maths
- operations


In [ ]:
x = [[1,2,3],[3,2,1]]
sums=0
for i in x:
    for j in i:
        sums+=j

print(sums)

print(x)

In [ ]:
import numpy as np

In [ ]:
x=np.array([[1,2,3],[3,4,5]])

#list has 11 funciton array has 100-200 functions 
# better
print(x)
print(type(x))
print(x.shape)

In [ ]:
print(x.sum())
print(x.sum(axis=0))  #sum of each column
print(x.sum(axis=1)) # sum of each row

In [7]:
a=np.array([1,2,3])#simple 1d matrix
b= np.array([[1,1],[2,2],[3,3]]) #2d matrix
c=np.array(([[[1,1],[2,2],[3,3]]])) #3d matrix

print(a.shape , a.ndim)
print(b.shape , b.ndim)
print(c.shape , c.ndim)

(3,) 1
(3, 2) 2
(1, 3, 2) 3


# Matrix creation 
- sequential
  - arange #advanced range
  - linspace  # linear spacing   utte scale ko linearly equally baaten  barabar barabar , upto kitte points wo specify kr skte h 

- random
  - rand
  - randint
  - uniform

to create an array 
# v 


In [12]:
x= np.arange(1,11,.5) #start , end ,step  #range wali values print ni hoti , i.e. 1 and 11 not included in output
print(x)

y=np.linspace(1,11,20) #start, end , number of points
print(y)

z=np.linspace(0,10,6) # range ki values print hoti h i.e. 0 and 10 also included in output
print (z)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]
[ 1.          1.52631579  2.05263158  2.57894737  3.10526316  3.63157895
  4.15789474  4.68421053  5.21052632  5.73684211  6.26315789  6.78947368
  7.31578947  7.84210526  8.36842105  8.89473684  9.42105263  9.94736842
 10.47368421 11.        ]
[ 0.  2.  4.  6.  8. 10.]


In [13]:
np.arange(1,11,.5).reshape(4,5) #arrange these values in 4x5 matrix



array([[ 1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5]])

In [14]:
np.arange(1,11,.5).reshape(5,5) #arrange these values in 5x5 matrix


ValueError: cannot reshape array of size 20 into shape (5,5)

In [15]:
np.arange(1,11,.5).reshape(5,4) #arrange these values in 5x4 matrix


array([[ 1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5]])

In [16]:
np.arange(-3.14,3.14,.2).reshape(8,4)

array([[-3.14, -2.94, -2.74, -2.54],
       [-2.34, -2.14, -1.94, -1.74],
       [-1.54, -1.34, -1.14, -0.94],
       [-0.74, -0.54, -0.34, -0.14],
       [ 0.06,  0.26,  0.46,  0.66],
       [ 0.86,  1.06,  1.26,  1.46],
       [ 1.66,  1.86,  2.06,  2.26],
       [ 2.46,  2.66,  2.86,  3.06]])

In [17]:
x1=np.array([[1,2,3],[4,5,6]])
x2=np.array([[4,2,3],[2,6,6]])

In [20]:
print(x1)
print(x2)
print(x1+x2)
print(x1-x2)
print(x1*x2)
print(x1/x2)
print(x1**x2)
print(x1//x2)
print(x1%x2)
#comparsion in numpy results in boolean array
print(x1>x2)
print(x1<x2)
print(x1>=x2)
print(x1<=x2)

[[1 2 3]
 [4 5 6]]
[[4 2 3]
 [2 6 6]]
[[ 5  4  6]
 [ 6 11 12]]
[[-3  0  0]
 [ 2 -1  0]]
[[ 4  4  9]
 [ 8 30 36]]
[[0.25       1.         1.        ]
 [2.         0.83333333 1.        ]]
[[    1     4    27]
 [   16 15625 46656]]
[[0 1 1]
 [2 0 1]]
[[1 0 0]
 [0 5 0]]
[[False False False]
 [ True False False]]
[[ True False False]
 [False  True False]]
[[False  True  True]
 [ True False  True]]
[[ True  True  True]
 [False  True  True]]


generate random data

In [24]:
a= np.random.rand(3,1)
a

array([[0.37720941],
       [0.44976629],
       [0.05241094]])

In [25]:
np.set_printoptions(precision=2)

In [26]:
a= np.random.rand(3,1)
a

array([[0.35],
       [0.23],
       [0.01]])

In [27]:
b = np.random.randint(0,10,(3,3))
b


array([[8, 4, 5],
       [0, 7, 6],
       [4, 7, 5]])

In [28]:
c=np.random.uniform(0,10,(3,3)) #
c


array([[8.  , 2.24, 7.24],
       [3.11, 4.69, 9.47],
       [4.01, 6.03, 8.81]])